import './style.css';
import {DEFAULTS,replay,ticket,parseCSV,csv} from '../lib/engine.js';
import {scenario} from '../lib/scenarios.js';
const $=s=>document.querySelector(s), money=(n,d=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:d}).format(n), num=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
const time=t=>new Date(t*1000).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config={...DEFAULTS},quotes=scenario(),result=replay(quotes,config),cursor=quotes.length-1,timer=null,uploaded=false;
let source='Synthetic / convergence',currentScenario='reversion';
document.querySelector('#app').innerHTML=`
<aside class="rail"><a class="brand" href="#"><span class="brand-mark">TG</span><span>TRADERS<br>GUILD</span></a><div class="rail-label">RESEARCH DESK / 01</div><nav><a class="active" href="#lab">◈ <span>Spread lab</span></a><a href="#market">⌁ <span>Market access</span></a><a href="#thesis">↗ <span>The trade thesis</span></a><a href="#ledger">≡ <span>Paper ledger</span></a></nav><div class="rail-bottom"><span class="status-dot"></span> RESEARCH BUILD<br><p>Architect market data<br>Hummingbot integration<br>Python + Node.js</p><a href="https://github.com/uwecerron/architect-hummingbot" target="_blank" rel="noreferrer">View source ↗</a></div></aside>
<main><header class="topbar"><span>COMPUTE / ENERGY LAB</span><div><span class="pill">PAPER ONLY</span><button id="export" class="quiet">Export replay ↓</button></div></header>
<section id="lab" class="intro"><div><div class="eyebrow">A NEW MARKET. A FAMILIAR QUESTION.</div><h1>What is compute<br>worth against energy<span>?</span></h1><p class="lead">Follow the gap between GPU rental futures and gas exposure.<br>Test the relationship before you trade it.</p></div><div class="intro-aside"><div class="edition">TRADERS GUILD / EXPERIMENT 001</div><p>H100 · DEC 2026<br><span>versus</span><br>UNG · PERPETUAL</p><div class="small">Relative-price research.<br>Not a calibrated electricity hedge.</div></div></section>
<div class="notice"><span class="notice-icon">◌</span><div><strong id="source">Synthetic / convergence</strong><span id="source-note">Constructed quotes, not historical returns. No exchange orders.</span></div><span class="pill">MODEL, NOT A SIGNAL SERVICE</span></div>
<section class="controls panel"><div><label for="scenario">Choose an experiment</label><select id="scenario"><option value="reversion">01 / Divergence reverses</option><option value="breakdown">02 / Relationship breaks</option><option value="friction">03 / Costs consume the move</option></select></div><div><label for="budget">Compute notional target ($)</label><input id="budget" type="number" value="10000" min="1000" max="1000000" step="1000"></div><div><label for="beta">Energy exposure ratio β</label><input id="beta" type="number" value="1" min="0.1" max="5" step="0.1"></div><div><label for="fees">Fee / leg / fill (bps)</label><input id="fees" type="number" value="5" min="0" max="100" step="1"></div><div><label for="slippage">Slippage / fill (bps)</label><input id="slippage" type="number" value="3" min="0" max="100" step="1"></div><button id="apply" class="dark">Run experiment ↗</button></section>
<div id="error" class="error" role="alert" hidden></div>
<div class="metrics"><article><div class="kicker">RELATIVE DEVIATION</div><div class="metric" id="z"></div><p id="signal-description"></p></article><article><div class="kicker">PAPER P&L · AFTER MODELED COSTS</div><div class="metric" id="pnl"></div><p id="pnl-note"></p></article><article><div class="kicker">MAXIMUM DRAWDOWN</div><div class="metric" id="drawdown"></div><p>Peak-to-trough, including open P&L</p></article><article><div class="kicker">ROUND-TRIP COST ESTIMATE</div><div class="metric" id="cost"></div><p id="cost-note"></p></article></div>
<section class="chart-grid"><article class="panel chart-main"><div class="panel-heading"><div><div class="kicker">01 / RELATIVE PRICES</div><h2>Two markets. One hypothesis.</h2></div><div class="legend"><span class="mint-dot"></span> H100 <span class="gold-dot"></span> UNG</div></div><div class="chart-sub">Both start at 100 · index of midquotes · <span id="range"></span> UTC</div><div id="prices-chart"></div><div class="replay-controls"><button id="play" class="dark">↺ Replay</button><input type="range" id="scrub" min="0" max="359" value="359" aria-label="Replay observation"><span id="clock"></span></div></article><article class="panel signal-panel"><div class="kicker">THE RESEARCH TICKET</div><h2 id="ticket-title">Watch the relationship</h2><p id="ticket-description"></p><div class="ticket-line"><span>Compute contracts</span><strong id="compute-count"></strong></div><div class="ticket-line"><span>Energy contracts</span><strong id="energy-count"></strong></div><div class="ticket-line"><span>Proposed gross exposure</span><strong id="gross"></strong></div><div class="ticket-line"><span>Move to cover costs*</span><strong id="breakeven"></strong></div><p class="footnote">*Approximation versus compute notional. β is an assumption. Contract rounding leaves unmatched exposure. No measured fill capacity.</p><div class="execution-lock">⊘ Execution disabled</div></article><article class="panel"><div class="panel-heading"><div><div class="kicker">02 / SIGNAL</div><h2>How unusual is the gap?</h2></div><span class="small">Previous 60 observations</span></div><div id="z-chart"></div><p class="footnote">Enter at ±2σ, close near zero. No entry beyond ±4σ. The current observation is excluded from its baseline.</p></article><article class="panel"><div class="panel-heading"><div><div class="kicker">03 / ACCOUNTING</div><h2>Does the idea pay?</h2></div><span class="small">USD · paper only</span></div><div id="pnl-chart"></div><p class="footnote">Includes modeled spreads, fees and slippage. Excludes funding, financing, market impact and margin liquidation. Dashed line: no trade ($0).</p></article></section>
<section id="market" class="panel market"><div class="panel-heading"><div><div class="kicker">FROM REPLAY TO OBSERVATION</div><h2>Connect the idea to the order book.</h2></div><span class="pill">READ-ONLY</span></div><div class="market-grid"><div><p>The demo uses the same native symbols as the Hummingbot monitor. Fetch an authenticated snapshot to inspect the two books. Observations never replace the synthetic chart silently.</p><div class="market-actions"><input id="access-token" type="password" placeholder="Demo access token (if configured)" autocomplete="off" aria-label="Demo market-data access token"><button id="fetch-market" class="dark">Check books ↗</button></div><p id="market-status" class="small" role="status">Not connected. No live liquidity or executable prices have been verified.</p><div id="book-view"></div></div><div class="integration"><h3>Hummingbot → Architect → Lab</h3><p>Uses <code>architect_perpetual</code> authentication and throttling. The monitor reads the dated GPU contract by native symbol; it does not pretend it is a perpetual.</p><label class="upload" for="upload">↑ Import quote CSV<input id="upload" type="file" accept=".csv,text/csv"></label><button id="download-input" class="quiet">Download current input CSV ↓</button><p class="small">Import the paired quotes saved by the Hummingbot or Node collector. Files stay in this browser. Imported data remains unverified.</p></div></div></section>
<section id="thesis" class="thesis"><div><div class="eyebrow">THE THESIS / AND HOW TO BREAK IT</div><h2>The useful question isn’t<br>“will AI get bigger?”</h2><p class="lead">It’s whether the price of its output is moving differently from the cost of its inputs, and whether that difference can be traded.</p><a href="/thesis.html" class="text-link" target="_blank">Read the research note ↗</a></div><div class="thesis-cards"><article><span>01</span><div><h3>The hypothesis</h3><p>If compute outpaces energy without a lasting change in demand or capacity, the gap may narrow. The research trade is short compute and long energy. Reverse the legs for the opposite divergence.</p></div></article><article><span>02</span><div><h3>The competing explanation</h3><p>GPU scarcity can lift rental prices while gas stays flat. Power contracts and regional grids can disconnect electricity costs from UNG. A wide gap can be rational and persistent.</p></div></article><article><span>03</span><div><h3>What would earn conviction</h3><p>A relationship that survives held-out data, actual funding and costs, executable two-leg depth, and different regimes. A low z-score alone proves none of those things.</p></div></article></div></section>
<section id="ledger" class="panel"><div class="panel-heading"><div><div class="kicker">AUDIT THE EXPERIMENT</div><h2>Every paper decision, visible.</h2></div><span class="small" id="event-count"></span></div><div class="table-scroll"><table><thead><tr><th>TIME / UTC</th><th>DECISION</th><th>DEVIATION</th><th>H100 CONTRACTS</th><th>UNG CONTRACTS</th><th>REALIZED P&L</th></tr></thead><tbody id="events"></tbody></table></div><div class="rules"><span>24h maximum hold</span><span>$500 cumulative loss threshold</span><span>5m cooldown</span><span>Stale quotes rejected</span></div><p class="footnote">Stops are decision rules, not guaranteed loss caps. A data gap while holding a position halts the simulation without inventing an exit fill.</p></section>
<section class="evidence"><div><div class="kicker">WHAT IS VERIFIED</div><h3>Contract definitions, not returns.</h3><p id="instrument-date">Architect instrument snapshot · September 26, 2026</p><p>H100 DEC: 730 GPU-hours per contract, Compute Desk benchmark. UNG: one ETF share per contract. ORNN is not this future’s settlement index.</p></div><div><a href="https://gateway.architect.exchange/api/instruments" target="_blank" rel="noreferrer">Architect instrument catalogue ↗</a><a href="https://hummingbot.org/exchanges/architect/" target="_blank" rel="noreferrer">Official Hummingbot connector ↗</a><a href="https://architect.co/insights/articles/intercommodity-spreads-crack-to-compute/" target="_blank" rel="noreferrer">Architect’s compute-spread framework ↗</a><a href="/instruments.json" target="_blank">Saved instrument evidence ↗</a><a href="https://github.com/uwecerron/architect-hummingbot" target="_blank" rel="noreferrer">Code, methodology and limitations ↗</a></div></section>
<footer><span>TRADERS GUILD / OPEN RESEARCH</span><p>Architect is a Traders Guild client. Independent experimental tooling. No established trading edge.</p></footer></main>`;
function chart(series,{height=190,thresholds=[],zero=false,format=v=>v.toFixed(1),label='Chart'}={}){
  const w=700,h=height,p={l:50,r:15,t:16,b:29},all=series.flatMap(s=>s.values.filter(Number.isFinite));if(!all.length)return '<div class="empty">Collecting observations for the signal…</div>';
  let low=Math.min(...all,...thresholds,...(zero?[0]:[])),high=Math.max(...all,...thresholds,...(zero?[0]:[]));const pad=(high-low)*.12||1;low-=pad;high+=pad;
  const len=Math.max(...series.map(s=>s.values.length)),x=i=>p.l+i/Math.max(1,len-1)*(w-p.l-p.r),y=v=>p.t+(high-v)/(high-low)*(h-p.t-p.b);
  let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}"><title>${esc(label)}</title>`;
  for(let i=0;i<4;i++){const v=low+(high-low)*i/3,yy=y(v);svg+=`<line x1="${p.l}" x2="${w-p.r}" y1="${yy}" y2="${yy}" stroke="#e7ebe8"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end">${esc(format(v))}</text>`;}
  for(const v of [...thresholds,...(zero?[0]:[])])svg+=`<line x1="${p.l}" x2="${w-p.r}" y1="${y(v)}" y2="${y(v)}" stroke="#aebcb7" stroke-dasharray="4 5"/>`;
  for(const s of series){let drawing=false;const path=s.values.map((v,i)=>{if(!Number.isFinite(v)){drawing=false;return '';}const cmd=drawing?'L':'M';drawing=true;return `${cmd}${x(i).toFixed(2)},${y(v).toFixed(2)}`;}).join(' ');svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2.5" stroke-linejoin="round"/>`;}
  for(const i of [0,Math.floor((len-1)/2),len-1])svg+=`<text x="${x(i)}" y="${h-5}" text-anchor="middle">${quotes[i]?time(quotes[i].timestamp):''}</text>`;
  return svg+'</svg>';
}
function render(){
 const qs=quotes.slice(0,cursor+1),rs=result.rows.slice(0,cursor+1),r=rs.at(-1),q=qs.at(-1);const t=ticket(q,config);
 $('#source').textContent=source;$('#source-note').textContent=uploaded?'User-supplied quotes, not independently verified. Paper results only.':'Constructed quotes, not historical returns. No exchange orders.';
 $('#z').textContent=r.z===null?'Warmup':num(r.z)+'σ';$('#signal-description').textContent=r.action==='HALTED'?'Halted: unresolved exposure / loss limit':r.z===null?`${rs.length} / ${config.lookback} baseline observations`:r.z>0?'Compute above its recent relative baseline':'Compute below its recent relative baseline';
 $('#pnl').textContent=money(r.equity,2);$('#pnl').className='metric '+(r.equity<0?'negative':'positive');$('#pnl-note').textContent=`${rs.filter(v=>v.action.startsWith('CLOSE_')).length} exits · ${r.compute_contracts?'open position marked':'flat'} · ${uploaded?'imported data':'synthetic data'}`;
 let peak=0,dd=0;for(const v of rs){peak=Math.max(peak,v.equity);dd=Math.max(dd,peak-v.equity);}$('#drawdown').textContent=money(dd,2);$('#cost').textContent=money(t.cost,2);$('#cost-note').textContent='At selected quote · excludes funding / impact';
 $('#range').textContent=time(qs[0].timestamp)+'–'+time(q.timestamp);$('#clock').textContent=time(q.timestamp)+' UTC';$('#scrub').value=cursor;
 const initialC=(quotes[0].compute_bid+quotes[0].compute_ask)/2,initialE=(quotes[0].energy_bid+quotes[0].energy_ask)/2;
 $('#prices-chart').innerHTML=chart([{color:'#128370',values:qs.map(q=>(q.compute_bid+q.compute_ask)/2/initialC*100)},{color:'#c49335',values:qs.map(q=>(q.energy_bid+q.energy_ask)/2/initialE*100)}],{height:270,label:'Constructed or imported compute and energy midquotes, indexed to 100'});
 $('#z-chart').innerHTML=chart([{color:'#128370',values:rs.map(r=>r.z)}],{thresholds:[-2,2],zero:true,label:'Relative deviation versus preceding observations'});
 $('#pnl-chart').innerHTML=chart([{color:'#52788f',values:rs.map(r=>r.equity)}],{zero:true,format:v=>money(v),label:'Paper P&L after modeled costs, no-trade baseline zero'});
 $('#compute-count').textContent=`${t.qc} / proposed size`;$('#energy-count').textContent=`${t.qe} / proposed size`;
 $('#gross').textContent=money(t.nc+t.ne);$('#breakeven').textContent=t.breakEven===null?'Below minimum size':num(t.breakEven,1)+' bps';
 $('#ticket-title').textContent=r.action==='HALTED'?'Experiment halted':r.compute_contracts<0?'Short compute / long energy':r.compute_contracts>0?'Long compute / short energy':'No open paper position';
 $('#ticket-description').textContent='Heading shows the current paper position. Sizing below is a fresh hypothetical ticket at this quote, not an executable order.';
 const events=rs.filter((v,i)=>!['WARMUP','HOLD'].includes(v.action)&&(v.action!=='HALTED'||rs[i-1]?.action!=='HALTED'));$('#event-count').textContent=events.length+' decision events';$('#events').innerHTML=events.slice(-30).reverse().map(v=>`<tr><td>${time(v.timestamp)}</td><td><span class="event ${v.action.startsWith('OPEN')?'enter':''}">${esc(v.action.replaceAll('_',' ').toLowerCase())}</span></td><td>${num(v.z)}σ</td><td>${v.compute_contracts}</td><td>${v.energy_contracts}</td><td>${money(v.realized_pnl,2)}</td></tr>`).join('')||'<tr><td colspan="6">No decisions yet. The model first needs 60 observations.</td></tr>';
}
function stop(){if(timer)clearInterval(timer);timer=null;$('#play').textContent='↺ Replay';}
function fail(e){$('#error').textContent=e.message;$('#error').hidden=false;}
function run(nextQuotes=quotes,nextConfig=config){try{const next=replay(nextQuotes,nextConfig);stop();quotes=nextQuotes;config=nextConfig;result=next;cursor=quotes.length-1;$('#scrub').max=cursor;$('#error').hidden=true;render();return true;}catch(e){fail(e);return false;}}
$('#scenario').onchange=e=>{const selected=e.target.value;if(run(scenario(selected))){uploaded=false;currentScenario=selected;source='Synthetic / '+({reversion:'convergence',breakdown:'structural break',friction:'cost drag'}[selected]);render();}};
$('#apply').onclick=()=>run(quotes,{...config,leg_usd:Number($('#budget').value),beta:Number($('#beta').value),fee_bps:Number($('#fees').value),slippage_bps:Number($('#slippage').value)});
$('#play').onclick=()=>{if(timer){stop();return;}if(cursor>=quotes.length-1)cursor=0;$('#play').textContent='Ⅱ Pause';timer=setInterval(()=>{cursor=Math.min(cursor+3,quotes.length-1);render();if(cursor===quotes.length-1)stop();},100);};
$('#scrub').oninput=e=>{stop();cursor=Number(e.target.value);render();};
function download(name,text){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>download('guild-'+(uploaded?'imported':'synthetic-'+currentScenario)+'-paper-replay.csv',csv(result.rows));
$('#download-input').onclick=()=>download((uploaded?'USER_SUPPLIED':'SYNTHETIC_'+currentScenario)+'-quotes.csv',csv(quotes));
$('#upload').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>8_000_000)throw Error('CSV exceeds 8 MB');const qs=parseCSV(await f.text());if(run(qs)){uploaded=true;source='Imported / '+f.name;render();}}catch(err){fail(err);}e.target.value='';};
$('#fetch-market').onclick=async()=>{
 const btn=$('#fetch-market');btn.disabled=true;$('#market-status').textContent='Requesting two validated book snapshots…';$('#book-view').innerHTML='';
 try{const token=$('#access-token').value;const r=await fetch('/api/market',{headers:token?{Authorization:'Bearer '+token}:{}});const s=await r.json();
 if(!r.ok||s.mode!=='observed'){$('#market-status').textContent=s.message||'Unavailable';return;}
 $('#market-status').textContent=`${s.environment.toUpperCase()} · observed ${new Date(s.received*1000).toISOString()} · snapshot only, not a live stream.`;
 $('#book-view').innerHTML='<div class="table-scroll"><table><thead><tr><th>SYMBOL</th><th>BID × SIZE</th><th>ASK × SIZE</th><th>AGE AT FETCH</th></tr></thead><tbody>'+s.books.map(b=>`<tr><td>${esc(b.symbol)}</td><td>${num(b.bid,3)} × ${b.bidSize}</td><td>${num(b.ask,3)} × ${b.askSize}</td><td>${num(s.received-b.timestamp,1)}s</td></tr>`).join('')+'</tbody></table></div><p class="small">Top-of-book sizes are displayed, not assumed fills. Run the collector to accumulate a replayable series.</p>';
 }catch{$('#market-status').textContent='Market endpoint unavailable. Run npm run dev or deploy on Vercel; static preview has no API.';}finally{btn.disabled=false;}
};
render();
